-- AlterTable
ALTER TABLE "transaction" ALTER COLUMN "systemDate" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "operationDate" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "uploadDate" SET DATA TYPE TIMESTAMPTZ;
